config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users

  as :user do
    get "signin" => 'devise/sessions#new'
    delete "signout" => 'devise/sessions#destroy'
    get 'signup' => 'devise/registrations#new'
end

  get 'feed', to: 'feed#show'

  resources :users, only: :show, param: :username do
    member do
      post 'follow', to: 'follows#create'
      delete 'unfollow', to: 'follows#destroy'
    end
  end
  



  
  resources :items do
    resources:comments
    member do
      
      post 'vote', to: 'votes#create'
      delete 'unvote', to: 'votes#destroy'

    end
  end

  resources :tweets
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  
  root 'pages#home'

  get 'about' => 'pages#about'

  

end

app/models/admin_authorization.rb
class AdminAuthorization<ActiveAdmin::AuthorizationAdapter

	def authorized?(action, subject=nil)
		user && user.admin?

	end




end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/models/follow.rb
class Follow < ApplicationRecord

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  
  validates :title, presence: true
    validates :text, presence: true

    acts_as_votable
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user


	validates :user, presence: true
    validates :content, presence: true

    has_attached_file :image
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

         has_many :tweets
         has_many :items
         has_many :comments, dependent: :destroy

       validates :username, presence: true, uniqueness: true, length: {minimum: 6}
       validates :name, presence: true

       acts_as_followable
       acts_as_follower
       acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?


  def access_denied(exception)
  	redirect_to root_path, alert: exception.message


  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name])
  end



end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
		before_action :authenticate_user!
		before_action :find_item
		before_action :find_comment, only: [:destroy, :edit, :update, :comment_owner]
		before_action :comment_owner, only: [:destroy, :edit, :update]



	def create
		@comment = @item.comments.create(params[:comment].permit(:content))
		@comment.user_id = current_user.id
		@comment.save
		
		if @comment.save
			redirect_to items_path(@item)
		else
			render 'new'
		end
		
	end


	def destroy
		@comment.destroy
		redirect_to item_path(@item)

	end


	def edit

	end


	def update 

		if (@comment.update(params[:comment].permit(:content)))
			redirect_to item_path(@item)

		else

			render 'edit'
		end

	end

	private

	def find_item
		@item = Item.find(params[:item_id])
	end


	def find_comment
		@comment = @item.comments.find(params[:id])


	end

	def comment_owner
		unless current_user.id == @comment.user_id
			flash[:notice] = "You are not able to pass, you must be the owner of the commment and also a member"
			redirect_to @item
		end

	end

	



end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
	before_action :authenticate_user!
  def show
  	@tweets= Tweet.where(user: current_user.all_following)
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :authenticate_user!
  def create
  	user= User.find_by(username: params[:username])
  	Follow.create(followable: user, follower: current_user)
  	redirect_to user_path(user.username), notice: "Successfully followed user"
  	
  end


  def destroy
  	user= User.find_by(username: params[:username])
  	Follow.find_by(followable: user, follower: current_user).destroy
  	redirect_to user_path(user.username), notice: "Successfully unfollowed user"
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
before_action :authenticate_user!, except: [:index]
  # GET /items
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])
    @comments = Comment.where(item_id: @item).order("created_at DESC")
  end

  # GET /items/new
  def new
    @item = current_user.items.new

  end

  # GET /items/1/edit
  def edit
    @item = current_user.items.find(params[:id])
  end

  # POST /items
  def create
    @item = current_user.items.new(item_params)

      if @item.save
         redirect_to @item, notice: 'Item was successfully created.' 
      else
        render :new 
    
    end
  end

  # PATCH/PUT /items/1
  def update
    @item = current_user.items.find(params[:id])
      if @item.update(item_params)
         redirect_to @item, notice: 'Item was successfully updated.' 
      else
         render :edit 
    end
  end

  # DELETE /items/1
  def destroy
    @item = current_user.items.find(params[:id])
    @item.destroy
       redirect_to items_url, notice: 'Item was successfully destroyed.' 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
   
    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit( :title, :url, :text)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController


before_action :authenticate_user!, except: [:index, :show]
  # GET /tweets
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  def show
    @tweet = Tweet.find(params[:id])
  end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.new
  end

  # GET /tweets/1/edit
  def edit
    @tweet = current_user.tweets.find(params[:id])
  end

  # POST /tweets
  def create
    @tweet = current_user.tweets.new(tweet_params)
    if @tweet.save
      redirect_to @tweet, notice: 'Tweet was successfully created.'
    else
      render :new 
    end
  end

  # PATCH/PUT /tweets/1
  def update
    @tweet = current_user.tweets.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to @tweet, notice: 'Tweet was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tweets/1
  def destroy
    @tweet = current_user.tweets.find(params[:id])
    @tweet.destroy
    redirect_to tweets_url, notice: 'Tweet was successfully destroyed.'
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:content, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find_by(username: params[:username])
  	@tweets = @user.tweets
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_user!

  def create
  	item=Item.find(params[:id])
    item.liked_by current_user
    redirect_to items_path, notice: "You successfully voted for an item"
  	
  end


  def destroy
    item = Item.find(params[:id])
    item.unliked_by current_user
    redirect_to items_path, notice: "You successfully unvoted for an item"

  end
  	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="container center">
	<div class="row">
		<div class="col-md-8">
			<div class="page-header">
				<small class="pull-right">This lesson has <%= pluralize( @comments.count ,"Comments" )%></small>
			</div>

				<div class="comments-list">
					<% @comments.each do |comment|%>
					<p><b><%= comment.user.username%></b></p>
					<p><%= auto_link(comment.content, :html => { :target => '_blank' })%></p>

					<% if current_user == comment.user %>
						<%= link_to "Delete ", [comment.item, comment], method: :delete,data: { confirm: 'Are you sure?' },class: "btn btn-sm btn-primary"%>
						<%= link_to 'Edit', edit_item_comment_path(comment.item, comment),class: "btn btn-sm btn-primary" %>
					<%end%>


					<%end%>


					<%= render 'comments/form'%>
				</div>

			</div>
	</div>
</div>

app/views/comments/_form.html.erb
<div class="container center">

	<%= form_for([@item, @item.comments.build]) do |f|%>



		<div class="form-group">
			<%= f.text_area :content,class: "form-control" %>
		</div>
		
		
			<div class="actions">
				<%=f.submit "Add", class: "btn btn-primary"  %>
			<br>
			</div>

		

	<%end%>
	

</div>

app/views/comments/edit.html.erb
<div class="container">
	<%= form_for([@item, @comment]) do |f|%>

		<div class="form-group">
			<%= f.text_field :content,class: "form-control"%>
		</div>
		
		<%if @comment.user==current_user %>
			<div class="actions">
			<%=f.submit "Update",  class: "btn btn-primary" %>
			</div>
		<%end%>

	<%end%>

</div>

app/views/items/_form.html.erb
<div class="container center">

  <div class='row'>
    <div class='col-xs-12'>


    <%= form_for(item, :html =>{class: 'form-horizontal',role: 'form'}) do |f| %>
      <% if item.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

          <ul>
          <% item.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>


     
      <div class='form-group'> 
        <div class='control-label col-sm-2'>
          <%= f.label :title %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title,class: 'form-control',placeholder: 'Title of lesson',autofocus: true%> 
        </div>
       </div>


      
      <div class='form-group'> 
          <div class='control-label col-sm-2'>
           <%= f.label :url %>
          </div>
          <div class="col-sm-8">
            <%= f.url_field :url,class: "form-control" %>
          </div>
      </div>

      
      <div class='form-group'> 
          <div class='control-label col-sm-2'>
            <%= f.label :text %>
          </div>
          <div class="col-sm-8">
        <%= f.text_area :text,rows: 8,class: 'form-control',placeholder:'Body of lesson'%> 
        </div>
      </div>

      <div class='form-group'> 
        <div class='col-sm-offset-4 col-sm-10'>
         <%= f.submit "Submit", class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>

    </div>

    </div>
 </div>

app/views/items/edit.html.erb
<div class="container">
	<h1 align="center">Editing Lesson</h1>

	<%= render 'form', item: @item %>
	<br>


	<p align="center"><%= link_to 'Show', @item,class: "btn btn-sm btn-primary" %> |
	<%= link_to 'Back', items_path,class: "btn btn-sm btn-primary" %></p>
</div>

app/views/items/index.html.erb
<div class="container">
  <h1 align="center">Lessons</h1>
  


    
      <% @items.each do |item| %>
        <div class="row" >
          <div class="col-xs-8 col-xs-offset-2">
            <div class="well well-lg">
                <div class="article-title">

                  <%= link_to item.title, item %>
                </div>
            

                <div class="article-body">

                  <%= truncate(item.text, length: 100) %>
                   <%=auto_link(item.url, :html => { :target => '_blank' }) %><br>
                  <%= item.votes_for.up.size %>

                  <% if user_signed_in?%>
                  <% if current_user.voted_up_on? item%>
                    <%= link_to 'unLike', unvote_item_path(item),method: :delete,class: "btn btn-sm btn-primary"%>
                      <%else%>

                    <%= link_to 'Like', vote_item_path(item), method: :post ,class: "btn btn-sm btn-primary"%>

                  <%end%>
                <%end%>

                  <div class="article-meta-details">

                    <small> Created by: <%= item.user.username if item.user %>, created:  
                            <%= time_ago_in_words(item.created_at)%> ago, updated: <%= time_ago_in_words(item.updated_at)%>


                                   
                   </small>
                  
                   </div>
                 </div>

              
              
             
 
              
              


             <div class="article-actions">   


              
                
                

                

                <%if item.user == current_user %>
                  <%= link_to 'Edit', edit_item_path(item),class: "btn btn-sm btn-primary" %>
                  <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-sm btn-danger" %>
                <%end%>
              
            
          </div>
        </div>
      </div>
    </div>
   

    
  

 

  <% end %>
 </div> 

  <br>
  <br>
 <h3 align="center"><%= link_to 'New Lesson', new_item_path,class: "btn btn-md btn-primary" %></h3>

app/views/items/new.html.erb
<div class="container">
	<h1 align="center">New Lesson</h1>

	<%= render 'form', item: @item %>
	<br>

	<%= link_to 'Back', items_path,class: "btn btn-sm btn-primary" %>
</div>

app/views/items/show.html.erb
<div class="container">
	<p>
	  <strong>User:</strong>
	  <%= @item.user.username %>
	</p>

	<h2 align="center"> Title: <%= @item.title%></h2>

	<div class="well col-xs-8 col-xs-offset-2">	

		<div class="article-actions">

		<%if @item.text?%>

			<p>
			 <h4 class="center description"> <strong>Text:</strong></h4>
			  <%=simple_format (@item.text) %>
			</p>

		<%end%>

		<p>
		  <p class="center description"><strong>Link:</strong></p>
		  <%= auto_link(@item.url, :html => { :target => '_blank' }) %>
		</p>

	

	<%= render 'comments/comment'%>
	<br>
	<br>

	<% if @item.user == current_user%>

		<p align="center"><%= link_to 'Edit', edit_item_path(@item), class: "btn btn-sm btn-primary"  %> |
		
	<%end%>
	<%= link_to 'Back', items_path,class: "btn btn-sm btn-primary" %></p>
</div>

app/views/tweets/_form.html.erb
<%= form_for(tweet, html: { multipart: true}) do |f| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content,class: "form-control" %>
  </div>



  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image,class: "form-control" %>
  </div>


  <div class="actions">
    <%= f.submit 'Submit', class: "btn btn-primary"%>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<div class="container">

	<h1>Editing Tweet</h1>

	<%= render 'form', tweet: @tweet %>

	<%= link_to 'Show', @tweet %> |
	<%= link_to 'Back', tweets_path %>
</div>

app/views/tweets/index.html.erb
<div class="container">
  
  <div class="row">
    <div class="col-md-4">
      <div class="card">
        <div class="card-block">

        <% if user_signed_in?%>
          <h4 class="card-title">Your Account</h4>
          <p class="card-text"><%= link_to current_user.username, user_path(current_user.username)  %></p>

          <%else%>

          <p class="card-text"><%= link_to "Sign up now!",signup_path  %></p>

        <%end%>

        </div>
        
      </div>
    </div>

    <div class="col-md-8">

      <% if user_signed_in?%>
        <%= link_to 'New Tweet', new_tweet_path %>
       <%end%>


       <ul class="list-group">
     
        <% @tweets.each do |tweet| %>
          <%= link_to tweet, class: "list-group-item list-group-item-action" do %>
            <h5 class="list-group-item-heading"><%= tweet.user.username%></h5>
            
            <% if tweet.image.present? %>
              <p><center> <%= image_tag tweet.image, class: "img-fluid"%></center></p>
            <%end%>
            
            <p class="list-group-item-text"><%= tweet.content %> </p>  

            

               
                    
              

            <%end%>


         <%end%>

        </ul>
       

      

     
     </div>

  </div>

</div>

app/views/tweets/new.html.erb
<div class="container">
	<h1>New Tweet</h1>

	<%= render 'form', tweet: @tweet %>

	<%= link_to 'Back', tweets_path %>

</div>

app/views/tweets/show.html.erb
<div class="container">

	<div class="row">
		<div class="offset-md-2 col-md-8">
			<div class="card card-block">
			  <h4 class="card-title"><%= link_to @tweet.user.username, user_path(@tweet.user.username) %></h4>

			 <center> <%= image_tag @tweet.image, class: "img-fluid"%></center>

			  <p class="card-text"><%= @tweet.content  %></p>

			  <%if @tweet.user==current_user %>

			  <%= link_to 'Edit', edit_tweet_path(@tweet), class: "card-link" %>
			  <%end%>
			  <%= link_to 'Back', tweets_path, class: "card-link" %>
			</div>
		
					
			
		</div>

	</div>

</div>

app/views/users/show.html.erb
<div class="container">
  
  <div class="row">
    <div class="col-md-4">
      <div class="card">
        <div class="card-block">
        <h4 class="card-title"><%= @user.username%></h4>
        <p class="card-text"><%= @user.name  %></p>
        </div>
        
      </div>
    </div>

    <div class="col-md-8">



       <ul class="list-group">
     
        <% @tweets.each do |tweet| %>
          <%= link_to tweet, class: "list-group-item list-group-item-action" do %>


            <h5 class="list-group-item-heading"><%= tweet.user.username%></h5>
            <p class="list-group-item-text"><%= tweet.content %>

            

               
                    
              </p>

            <%end%>


         <%end%>

        </ul>
       

      

     
     </div>

  </div>

</div>