config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users

  as :user do
    get "signin" => 'devise/sessions#new'
    delete "signout" => 'devise/sessions#destroy'
    get 'signup' => 'devise/registrations#new'
end

  get 'feed', to: 'feed#show'

  resources :users, only: :show, param: :username do
    member do
      post 'follow', to: 'follows#create'
      delete 'unfollow', to: 'follows#destroy'
    end
  end
  



  
  resources :items do
    resources:comments
    member do
      
      post 'vote', to: 'votes#create'
      delete 'unvote', to: 'votes#destroy'

    end
  end

  resources :tweets
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  
  root 'pages#home'

  get 'about' => 'pages#about'

  

end

app/models/admin_authorization.rb
class AdminAuthorization<ActiveAdmin::AuthorizationAdapter

	def authorized?(action, subject=nil)
		user && user.admin?

	end




end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/models/follow.rb
class Follow < ApplicationRecord

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  
  validates :title, presence: true
    validates :text, presence: true

    acts_as_votable
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user


	validates :user, presence: true
    validates :content, presence: true

    has_attached_file :image
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

         has_many :tweets
         has_many :items
         has_many :comments, dependent: :destroy

       validates :username, presence: true, uniqueness: true, length: {minimum: 6}
       validates :name, presence: true

       acts_as_followable
       acts_as_follower
       acts_as_voter
end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
	before_action :authenticate_user!
  def show
  	@tweets= Tweet.where(user: current_user.all_following)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
before_action :authenticate_user!, except: [:index]
  # GET /items
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])
    @comments = Comment.where(item_id: @item).order("created_at DESC")
  end

  # GET /items/new
  def new
    @item = current_user.items.new

  end

  # GET /items/1/edit
  def edit
    @item = current_user.items.find(params[:id])
  end

  # POST /items
  def create
    @item = current_user.items.new(item_params)

      if @item.save
         redirect_to @item, notice: 'Item was successfully created.' 
      else
        render :new 
    
    end
  end

  # PATCH/PUT /items/1
  def update
    @item = current_user.items.find(params[:id])
      if @item.update(item_params)
         redirect_to @item, notice: 'Item was successfully updated.' 
      else
         render :edit 
    end
  end

  # DELETE /items/1
  def destroy
    @item = current_user.items.find(params[:id])
    @item.destroy
       redirect_to items_url, notice: 'Item was successfully destroyed.' 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
   
    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit( :title, :url, :text)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController


before_action :authenticate_user!, except: [:index, :show]
  # GET /tweets
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  def show
    @tweet = Tweet.find(params[:id])
  end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.new
  end

  # GET /tweets/1/edit
  def edit
    @tweet = current_user.tweets.find(params[:id])
  end

  # POST /tweets
  def create
    @tweet = current_user.tweets.new(tweet_params)
    if @tweet.save
      redirect_to @tweet, notice: 'Tweet was successfully created.'
    else
      render :new 
    end
  end

  # PATCH/PUT /tweets/1
  def update
    @tweet = current_user.tweets.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to @tweet, notice: 'Tweet was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tweets/1
  def destroy
    @tweet = current_user.tweets.find(params[:id])
    @tweet.destroy
    redirect_to tweets_url, notice: 'Tweet was successfully destroyed.'
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:content, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find_by(username: params[:username])
  	@tweets = @user.tweets
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_user!

  def create
  	item=Item.find(params[:id])
    item.liked_by current_user
    redirect_to items_path, notice: "You successfully voted for an item"
  	
  end


  def destroy
    item = Item.find(params[:id])
    item.unliked_by current_user
    redirect_to items_path, notice: "You successfully unvoted for an item"

  end
  	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Group</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag'application', 'data-turbolinks-track': 'reload' %>

<style>
 a:link, a {text-decoration: none;} 
</style>

<script type="text/javascript">
</script>

 <meta name="viewport" content="width=device-width, initial-scale=1">

  </head>


  <body>


    <!-- Navigation Bar -->


    

  <nav class="navbar navbar-dark bg-inverse" >
       <div class="container-fluid">
        <div class="navbar-header" >
         <%= link_to "Musketeer", root_path,class: "navbar-brand",id: "logo"  %>
         </div>


         <ul class="nav navbar-nav" id="myTopnav" >
           
           <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
           
           <li class="nav-item"><%= link_to "Tweets", tweets_path, class: "nav-link" %></li>

           <li class="nav-item"><%= link_to "Lessons", items_path, class: "nav-link" %></li>

           <li class="nav-item"><%= link_to "Feed", feed_path, class: "nav-link" %></li>
            



            <%if user_signed_in? %>

              <li class="nav-item pull-md-right"><%= link_to "Log out", signout_path,method: :delete, class: "nav-link" %></li>


          <%else%>
          <li class="nav-item pull-md-right"><%= link_to "Sign up", signup_path, class: "btn btn-primary btn-sm active" %></li>

            <li class="nav-item pull-md-right "><%= link_to "Sign in", signin_path, class: "btn btn-default btn-sm " %></li>
            
          <%end%>

            <li class="icon">
              <a href="javascript:void(0);" onclick="myFunction()" style="font-size:25px;" color="white" >&#9776;</a>
           </li>
          

         </ul>
       </div>
     </nav>



    <!-- Flasf Messages  -->
    <% flash.each do |name, message|%>
      <%= content_tag(:div,message,class:"alert alert-info #{name}")%>
     <%end%>

    <!-- Page Content -->
    
    <%= yield %>
    
    <!-- Footer -->
    <footer class="small text-muted">
      <div class="container">
        <hr>
        <center>
          <p>© 2016 Draganoiu Andrei</p>
        </center>
      </div>
    </footer>

  </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
    <div class="container">
        <h1>About us</h1>
        
    </div>
</div>

app/views/pages/home.html.erb
<%if user_signed_in?%>

<div class="jumbotron jumbotron-home">
    <div class="container">                
        <h1><font color="white">Welcome back!</font></h1>   
    </div>

    <%else%>

    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        <li data-target="#carousel-example-generic" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="carousel-item active">
          <img src="https://s3.amazonaws.com/draganoiu/tweets/images/000/000/001/original/6.jpg" alt="First slide">
      </div>
      <div class="carousel-item">
          <img src="https://s3.amazonaws.com/draganoiu/tweets/images/000/000/001/original/4.jpg" alt="Second slide">
      </div>
      <div class="carousel-item">
          <img src="https://s3.amazonaws.com/draganoiu/tweets/images/000/000/001/original/5.jpg" alt="Third slide">
      </div>
      <div class="carousel-item">
          <img src="https://s3.amazonaws.com/draganoiu/tweets/images/000/000/001/original/bg2.jpg" alt="Third slide">
      </div>
  </div>
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="icon-prev" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
</a>
<a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="icon-next" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
</a>
</div>



<%end%>